### ISSUE TITLE
More clear description

### ISSUE THREAD

**Issue by ai** [shauns/postcss-math#1]
Whta is difference with [postcss-calc](https://github.com/postcss/postcss-calc)?

**Comment by shauns** [comment]
They're (deliberately) trying to work towards the `calc(...)` standard, so for instance it doesn't support things like exponentials at the moment. This wraps up math.js so you have a wider range of things you can do.

**Comment by ai** [comment]
Nice. I think it would be nice to say explicit.

**Comment by shauns** [comment]
Popped something in the README. Thanks for the input!
