### ISSUE TITLE
percentage does not work?

### ISSUE THREAD

**Issue by hkirsman** [shauns/postcss-math#10]
This works:
font-size: resolve(100 \* strip($font-size-small) / strip($font-size-base) \* 1px)
but this fails
font-size: resolve(100 \* strip($font-size-small) / strip($font-size-base) \* 1%)

I get "Unexpected end of expression".

**Comment by shauns** [comment]
Thanks for raising -- this syntax isn't supported by Math.js. You can't do e.g. `100 * 1%` in that library. Here's a good site for testing: http://mathnotepad.com/ . Sorry!

**Comment by good-idea** [comment]
you can still concatenate: `left: resolve(100 / 9)%;` -> `left: 11.11111111111111%`
