### ISSUE TITLE
Resolve function conflicts with postcss-assets

### ISSUE THREAD

**Issue by timkelty** [shauns/postcss-math#14]
I'd like to use this plugin, but I'm also using `postcss-assets`, which has a resolve function.

Any idea to make this configurable, or possibly just changing it, since it seems `postcss-assets` is pretty heavily used.

**Comment by shauns** [comment]
Hi -- this should be fixed in 0.0.8; thanks for letting me know!

**Comment by timkelty** [comment]
Thanks so much!
